In [76]:
import pandas as pd

In [77]:
# Combine the two datasets
df_train = pd.read_csv("Titanic_datasets/train.csv")
df_test = pd.read_csv("Titanic_datasets/test.csv")
# Menggabungkan df_train dan df_test ke dfmerged
df = pd.concat([df_train, df_test], sort = False)
df.reset_index(drop = False, inplace = True)
df.to_csv("Titanic_datasets/dftitanic.csv", index = False)

In [78]:
df = pd.read_csv('Titanic_datasets/dftitanic.csv')
df.head()

index  PassengerId  Survived  Pclass  \
0      0            1       0.0       3   
1      1            2       1.0       1   
2      2            3       1.0       3   
3      3            4       1.0       1   
4      4            5       0.0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [79]:
df.isna().sum()

index             0
PassengerId       0
Survived        418
Pclass            0
Name              0
Sex               0
Age             263
SibSp             0
Parch             0
Ticket            0
Fare              1
Cabin          1014
Embarked          2
dtype: int64

In [80]:
def missing_values_report(df):
	for index, missing in enumerate(df.isna().sum()):
		print(f"{df.columns[index]:11} | {missing * 100 / len(df):.2f}%")

missing_values_report(df)

index       | 0.00%
PassengerId | 0.00%
Survived    | 31.93%
Pclass      | 0.00%
Name        | 0.00%
Sex         | 0.00%
Age         | 20.09%
SibSp       | 0.00%
Parch       | 0.00%
Ticket      | 0.00%
Fare        | 0.08%
Cabin       | 77.46%
Embarked    | 0.15%


In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   index        1309 non-null   int64  
 1   PassengerId  1309 non-null   int64  
 2   Survived     891 non-null    float64
 3   Pclass       1309 non-null   int64  
 4   Name         1309 non-null   object 
 5   Sex          1309 non-null   object 
 6   Age          1046 non-null   float64
 7   SibSp        1309 non-null   int64  
 8   Parch        1309 non-null   int64  
 9   Ticket       1309 non-null   object 
 10  Fare         1308 non-null   float64
 11  Cabin        295 non-null    object 
 12  Embarked     1307 non-null   object 
dtypes: float64(3), int64(5), object(5)
memory usage: 133.1+ KB


In [82]:
df = df.dropna(subset=['Survived', 'Embarked'], axis = 0)

In [83]:
# Drop cabin because it has too many missing values (column)
df = df.drop(['Cabin'], axis=1)

In [84]:
# check the missing values
missing_values_report(df)

index       | 0.00%
PassengerId | 0.00%
Survived    | 0.00%
Pclass      | 0.00%
Name        | 0.00%
Sex         | 0.00%
Age         | 19.91%
SibSp       | 0.00%
Parch       | 0.00%
Ticket      | 0.00%
Fare        | 0.00%
Embarked    | 0.00%


In [85]:
# Isi age berdasarkan mean dari keseluruhan age
# df['Age'].fillna(df['Age'].mean(skipna=True), inplace=True) # Gunakan mean karena data numerik
# Isi age berdasarkan Survived
df['Age'] = df.groupby('Survived')['Age'].transform(lambda x: x.fillna(x.mean())).round()

In [86]:
missing_values_report(df)

index       | 0.00%
PassengerId | 0.00%
Survived    | 0.00%
Pclass      | 0.00%
Name        | 0.00%
Sex         | 0.00%
Age         | 0.00%
SibSp       | 0.00%
Parch       | 0.00%
Ticket      | 0.00%
Fare        | 0.00%
Embarked    | 0.00%


In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   index        889 non-null    int64  
 1   PassengerId  889 non-null    int64  
 2   Survived     889 non-null    float64
 3   Pclass       889 non-null    int64  
 4   Name         889 non-null    object 
 5   Sex          889 non-null    object 
 6   Age          889 non-null    float64
 7   SibSp        889 non-null    int64  
 8   Parch        889 non-null    int64  
 9   Ticket       889 non-null    object 
 10  Fare         889 non-null    float64
 11  Embarked     889 non-null    object 
dtypes: float64(3), int64(5), object(4)
memory usage: 90.3+ KB


In [88]:
print(df['Embarked'].value_counts())

mode = df['Embarked'].value_counts().idxmax()
print(f"Mode: {mode}")

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64
Mode: S


In [89]:
df['Survived'].value_counts() # Data imbalance

Survived
0.0    549
1.0    340
Name: count, dtype: int64

In [90]:
# Drop unused columns that don't have any correlation with the label
df = df.drop(['Name', 'Ticket', 'PassengerId'], axis=1)
# Label Encoder
from sklearn.preprocessing import LabelEncoder
# Binary encoder
from sklearn.preprocessing import LabelBinarizer
# Encoding (Target Encoder for Embarked)
# remove text columns and the PassengerId
# Turn the 'Sex' feature into binary using label encoder
label_encoder = LabelEncoder()
binary_encoder = LabelBinarizer()
df['Sex'] = binary_encoder.fit_transform(df['Sex'])
# One hot encode the Embarked feature
df = pd.get_dummies(df, columns=['Embarked'], dtype=int)

In [91]:
df.head()

index  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_C  \
0      0       0.0       3    1  22.0      1      0   7.2500           0   
1      1       1.0       1    0  38.0      1      0  71.2833           1   
2      2       1.0       3    0  26.0      0      0   7.9250           0   
3      3       1.0       1    0  35.0      1      0  53.1000           0   
4      4       0.0       3    1  35.0      0      0   8.0500           0   

   Embarked_Q  Embarked_S  
0           0           1  
1           0           0  
2           0           1  
3           0           1  
4           0           1

In [92]:
# Export file yang sudah bersih
df.to_csv("Titanic_datasets/dfclean.csv", index = False)

In [93]:
# Detect Outliers using IQR method
def find_outliers_IQR(df):
   q1=df.quantile(0.25)
   q3=df.quantile(0.75)
   IQR=q3-q1
   outliers = df[(df<(q1-1.5*IQR)) | (df>(q3+1.5*IQR))]
   return outliers

find_outliers_IQR(df)


index  Survived  Pclass  Sex  Age  SibSp  Parch     Fare  Embarked_C  \
0      NaN       NaN     NaN  NaN  NaN    NaN    NaN      NaN         NaN   
1      NaN       NaN     NaN  NaN  NaN    NaN    NaN  71.2833         1.0   
2      NaN       NaN     NaN  NaN  NaN    NaN    NaN      NaN         NaN   
3      NaN       NaN     NaN  NaN  NaN    NaN    NaN      NaN         NaN   
4      NaN       NaN     NaN  NaN  NaN    NaN    NaN      NaN         NaN   
..     ...       ...     ...  ...  ...    ...    ...      ...         ...   
886    NaN       NaN     NaN  NaN  NaN    NaN    NaN      NaN         NaN   
887    NaN       NaN     NaN  NaN  NaN    NaN    NaN      NaN         NaN   
888    NaN       NaN     NaN  NaN  NaN    NaN    2.0      NaN         NaN   
889    NaN       NaN     NaN  NaN  NaN    NaN    NaN      NaN         1.0   
890    NaN       NaN     NaN  NaN  NaN    NaN    NaN      NaN         NaN   

     Embarked_Q  Embarked_S  
0           NaN         NaN  
1           NaN         NaN  
2           NaN         NaN  
3           NaN         NaN  
4           NaN         NaN  
..          ...         ...  
886         NaN         NaN  
887         NaN         NaN  
888         NaN         NaN  
889         NaN         NaN  
890         1.0         NaN  

[889 rows x 11 columns]

In [94]:
import numpy as np

def handle_outliers(df):
    for i in df.columns:
        if np.issubdtype(df[i].dtype, np.number):
            Q1 = df[i].quantile(0.25)
            Q3 = df[i].quantile(0.75)
            IQR = Q3 - Q1

            lower_bound = Q1 - 1.5 * IQR
            upper_bound = Q3 + 1.5 * IQR
            # Winsorization
            df[i] = np.where(df[i] < lower_bound, lower_bound, df[i])
            df[i] = np.where(df[i] > upper_bound, upper_bound, df[i])

            print(f"Column {i} has been processed")
        else:
            print(f"Column {i} is not numeric, skipping...")

handle_outliers(df)



Column index has been processed
Column Survived has been processed
Column Pclass has been processed
Column Sex has been processed
Column Age has been processed
Column SibSp has been processed
Column Parch has been processed
Column Fare has been processed
Column Embarked_C has been processed
Column Embarked_Q has been processed
Column Embarked_S has been processed


In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   index       889 non-null    float64
 1   Survived    889 non-null    float64
 2   Pclass      889 non-null    float64
 3   Sex         889 non-null    float64
 4   Age         889 non-null    float64
 5   SibSp       889 non-null    float64
 6   Parch       889 non-null    float64
 7   Fare        889 non-null    float64
 8   Embarked_C  889 non-null    float64
 9   Embarked_Q  889 non-null    float64
 10  Embarked_S  889 non-null    float64
dtypes: float64(11)
memory usage: 83.3 KB


In [97]:
# Scaling the data using StandarScaler -> mean = 0, std = 1 -> value range [-1, 1]
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = df.drop(['Survived'], axis=1)
y = df['Survived']

X = scaler.fit_transform(X)

In [98]:
# Train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =  train_test_split(X, y,random_state = 42, test_size = 0.2)
# print(X_train.shape)
# print(X_test.shape)
# print(y_train.shape)
# print(y_test.shape)

# Oversampling
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=0)
X_train,y_train = sm.fit_resample(X_train, y_train)


In [99]:
# function to calculate the error values
#MSE, RMSE, and R-squared
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

def error_values(): 
    mse = mean_squared_error(y_test, y_pred)
    rmse = sqrt(mse)
    r2 = r2_score(y_test, y_pred)
    print('Mean Squared Error: ', mse)
    print('Root Mean Squared Error: ', rmse)
    print('R-squared: ', r2)

In [100]:
# Implement Decision Tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

# Decision Tree
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
y_pred = dt.predict(X_test)
print('Accuracy: ', accuracy_score(y_test, y_pred))
print('Classification Report: \n', classification_report(y_test, y_pred))
print('Confusion Matrix: \n', confusion_matrix(y_test, y_pred))

error_values()

Accuracy:  0.7359550561797753
Classification Report: 
               precision    recall  f1-score   support

         0.0       0.82      0.72      0.77       109
         1.0       0.63      0.75      0.69        69

    accuracy                           0.74       178
   macro avg       0.73      0.74      0.73       178
weighted avg       0.75      0.74      0.74       178

Confusion Matrix: 
 [[79 30]
 [17 52]]
Mean Squared Error:  0.2640449438202247
Root Mean Squared Error:  0.5138530371810842
R-squared:  -0.11235208084031356


In [101]:
# Implement KNN
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

print('Accuracy: ', accuracy_score(y_test, y_pred))
print('Classification Report: \n', classification_report(y_test, y_pred))
print('Confusion Matrix: \n', confusion_matrix(y_test, y_pred))

error_values()

Accuracy:  0.7584269662921348
Classification Report: 
               precision    recall  f1-score   support

         0.0       0.84      0.75      0.79       109
         1.0       0.66      0.77      0.71        69

    accuracy                           0.76       178
   macro avg       0.75      0.76      0.75       178
weighted avg       0.77      0.76      0.76       178

Confusion Matrix: 
 [[82 27]
 [16 53]]
Mean Squared Error:  0.24157303370786518
Root Mean Squared Error:  0.49150079726066076
R-squared:  -0.017683818641137883


In [102]:
# Implement Naive Bayes
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import CategoricalNB

nb = GaussianNB()
nb.fit(X_train, y_train)
y_pred = nb.predict(X_test)

print('Accuracy: ', accuracy_score(y_test, y_pred))
print('Classification Report: \n', classification_report(y_test, y_pred))
print('Confusion Matrix: \n', confusion_matrix(y_test, y_pred))

error_values()

Accuracy:  0.7584269662921348
Classification Report: 
               precision    recall  f1-score   support

         0.0       0.86      0.72      0.79       109
         1.0       0.65      0.81      0.72        69

    accuracy                           0.76       178
   macro avg       0.75      0.77      0.75       178
weighted avg       0.78      0.76      0.76       178

Confusion Matrix: 
 [[79 30]
 [13 56]]
Mean Squared Error:  0.24157303370786518
Root Mean Squared Error:  0.49150079726066076
R-squared:  -0.017683818641137883
